const challenges = [
  {
    planetId: 1,
    planetImg: 'https://example.com/image1.jpg',
    category: 'EXERCISE',
    name: 'Morning Run',
    content: 'Join us for a daily morning run challenge!',
    startDate: [2023, 7, 1],
    endDate: [2023, 7, 31],
    currentParticipants: 10,
    maxParticipants: 10
  },
  {
    planetId: 2,
    planetImg: 'https://example.com/image2.jpg',
    category: 'LIFE',
    name: 'Healthy Eating',
    content: 'Challenge yourself to eat healthy every day.',
    startDate: [2023, 8, 1],
    endDate: [2023, 8, 31],
    currentParticipants: 5,
    maxParticipants: 8
  },
  {
    planetId: 3,
    planetImg: 'https://example.com/image3.jpg',
    category: 'BEAUTY',
    name: 'Skincare Routine',
    content: 'Follow a daily skincare routine for glowing skin.',
    startDate: [2023, 9, 1],
    endDate: [2023, 9, 30],
    currentParticipants: 7,
    maxParticipants: 9
  },
  {
    planetId: 4,
    planetImg: 'https://example.com/image4.jpg',
    category: 'STUDY',
    name: 'Daily Coding',
    content: 'Improve your coding skills with daily practice.',
    startDate: [2023, 10, 1],
    endDate: [2023, 10, 31],
    currentParticipants: 3,
    maxParticipants: 7
  },
  {
    planetId: 5,
    planetImg: 'https://example.com/image5.jpg',
    category: 'ETC',
    name: 'Meditation',
    content: 'Meditate daily for a calm and peaceful mind.',
    startDate: [2023, 11, 1],
    endDate: [2023, 11, 30],
    currentParticipants: 9,
    maxParticipants: 10
  },
  {
    planetId: 6,
    planetImg: 'https://example.com/image6.jpg',
    category: 'EXERCISE',
    name: 'Yoga',
    content: 'Start your day with a relaxing yoga session.',
    startDate: [2023, 7, 1],
    endDate: [2023, 7, 31],
    currentParticipants: 6,
    maxParticipants: 10
  },
  {
    planetId: 7,
    planetImg: 'https://example.com/image7.jpg',
    category: 'LIFE',
    name: 'No Sugar',
    content: 'Cut out sugar for a month and feel the difference.',
    startDate: [2023, 8, 1],
    endDate: [2023, 8, 31],
    currentParticipants: 5,
    maxParticipants: 8
  },
  {
    planetId: 8,
    planetImg: 'https://example.com/image8.jpg',
    category: 'BEAUTY',
    name: 'Hair Care',
    content: 'Take good care of your hair with a daily routine.',
    startDate: [2023, 9, 1],
    endDate: [2023, 9, 30],
    currentParticipants: 6,
    maxParticipants: 9
  },
  {
    planetId: 9,
    planetImg: 'https://example.com/image9.jpg',
    category: 'STUDY',
    name: 'Read a Book',
    content: 'Read a book a day and expand your knowledge.',
    startDate: [2023, 10, 1],
    endDate: [2023, 10, 31],
    currentParticipants: 4,
    maxParticipants: 7
  },
  {
    planetId: 10,
    planetImg: 'https://example.com/image10.jpg',
    category: 'ETC',
    name: 'Journaling',
    content: 'Write in your journal every day.',
    startDate: [2023, 11, 1],
    endDate: [2023, 11, 30],
    currentParticipants: 7,
    maxParticipants: 10
  },
  {
    planetId: 11,
    planetImg: 'https://example.com/image11.jpg',
    category: 'EXERCISE',
    name: 'Cycling',
    content: 'Cycle every day and stay fit.',
    startDate: [2023, 7, 1],
    endDate: [2023, 7, 31],
    currentParticipants: 4,
    maxParticipants: 8
  },
  {
    planetId: 12,
    planetImg: 'https://example.com/image12.jpg',
    category: 'LIFE',
    name: 'Daily Walk',
    content: 'Walk at least 10,000 steps every day.',
    startDate: [2023, 8, 1],
    endDate: [2023, 8, 31],
    currentParticipants: 6,
    maxParticipants: 9
  },
  {
    planetId: 13,
    planetImg: 'https://example.com/image13.jpg',
    category: 'BEAUTY',
    name: 'Daily Makeup Free',
    content: 'Go makeup-free for a month and let your skin breathe.',
    startDate: [2023, 9, 1],
    endDate: [2023, 9, 30],
    currentParticipants: 3,
    maxParticipants: 7
  },
  {
    planetId: 14,
    planetImg: 'https://example.com/image14.jpg',
    category: 'STUDY',
    name: 'Language Learning',
    content: 'Learn a new language with daily practice.',
    startDate: [2023, 10, 1],
    endDate: [2023, 10, 31],
    currentParticipants: 5,
    maxParticipants: 9
  },
  {
    planetId: 15,
    planetImg: 'https://example.com/image15.jpg',
    category: 'ETC',
    name: 'Digital Detox',
    content: 'Stay away from digital devices for a month.',
    startDate: [2023, 11, 1],
    endDate: [2023, 11, 30],
    currentParticipants: 8,
    maxParticipants: 10
  },
  {
    planetId: 16,
    planetImg: 'https://example.com/image16.jpg',
    category: 'EXERCISE',
    name: 'Strength Training',
    content: 'Build muscle with daily strength training exercises.',
    startDate: [2023, 7, 1],
    endDate: [2023, 7, 31],
    currentParticipants: 5,
    maxParticipants: 8
  },
  {
    planetId: 17,
    planetImg: 'https://example.com/image17.jpg',
    category: 'LIFE',
    name: 'Hydration',
    content: 'Drink at least 2 liters of water every day.',
    startDate: [2023, 8, 1],
    endDate: [2023, 8, 31],
    currentParticipants: 6,
    maxParticipants: 9
  },
  {
    planetId: 18,
    planetImg: 'https://example.com/image18.jpg',
    category: 'BEAUTY',
    name: 'Nail Care',
    content: 'Maintain healthy nails with a daily care routine.',
    startDate: [2023, 9, 1],
    endDate: [2023, 9, 30],
    currentParticipants: 4,
    maxParticipants: 7
  },
  {
    planetId: 19,
    planetImg: 'https://example.com/image19.jpg',
    category: 'STUDY',
    name: 'Math Practice',
    content: 'Improve your math skills with daily practice.',
    startDate: [2023, 10, 1],
    endDate: [2023, 10, 31],
    currentParticipants: 5,
    maxParticipants: 8
  },
  {
    planetId: 20,
    planetImg: 'https://example.com/image20.jpg',
    category: 'ETC',
    name: 'Volunteer',
    content: 'Volunteer every day and make a difference.',
    startDate: [2023, 11, 1],
    endDate: [2023, 11, 30],
    currentParticipants: 7,
    maxParticipants: 10
  },
  {
    planetId: 21,
    planetImg: 'https://example.com/image21.jpg',
    category: 'EXERCISE',
    name: 'Swimming',
    content: 'Swim daily for a full-body workout.',
    startDate: [2023, 7, 1],
    endDate: [2023, 7, 31],
    currentParticipants: 4,
    maxParticipants: 7
  },
  {
    planetId: 22,
    planetImg: 'https://example.com/image22.jpg',
    category: 'LIFE',
    name: 'Mindfulness',
    content: 'Practice mindfulness and stay present.',
    startDate: [2023, 8, 1],
    endDate: [2023, 8, 31],
    currentParticipants: 6,
    maxParticipants: 9
  },
  {
    planetId: 23,
    planetImg: 'https://example.com/image23.jpg',
    category: 'BEAUTY',
    name: 'Natural Beauty',
    content: 'Embrace your natural beauty with minimal products.',
    startDate: [2023, 9, 1],
    endDate: [2023, 9, 30],
    currentParticipants: 3,
    maxParticipants: 6
  },
  {
    planetId: 24,
    planetImg: 'https://example.com/image24.jpg',
    category: 'STUDY',
    name: 'Writing Practice',
    content: 'Improve your writing skills with daily practice.',
    startDate: [2023, 10, 1],
    endDate: [2023, 10, 31],
    currentParticipants: 5,
    maxParticipants: 7
  },
  {
    planetId: 25,
    planetImg: 'https://example.com/image25.jpg',
    category: 'ETC',
    name: 'Cooking',
    content: 'Cook a new recipe every day.',
    startDate: [2023, 11, 1],
    endDate: [2023, 11, 30],
    currentParticipants: 8,
    maxParticipants: 10
  },
  {
    planetId: 26,
    planetImg: 'https://example.com/image26.jpg',
    category: 'EXERCISE',
    name: 'Pilates',
    content: 'Strengthen your core with daily Pilates sessions.',
    startDate: [2023, 7, 1],
    endDate: [2023, 7, 31],
    currentParticipants: 5,
    maxParticipants: 7
  },
  {
    planetId: 27,
    planetImg: 'https://example.com/image27.jpg',
    category: 'LIFE',
    name: 'Gratitude',
    content: 'Write down what you are grateful for every day.',
    startDate: [2023, 8, 1],
    endDate: [2023, 8, 31],
    currentParticipants: 4,
    maxParticipants: 8
  },
  {
    planetId: 28,
    planetImg: 'https://example.com/image28.jpg',
    category: 'BEAUTY',
    name: 'DIY Beauty',
    content: 'Create your own beauty products at home.',
    startDate: [2023, 9, 1],
    endDate: [2023, 9, 30],
    currentParticipants: 3,
    maxParticipants: 6
  },
  {
    planetId: 29,
    planetImg: 'https://example.com/image29.jpg',
    category: 'STUDY',
    name: 'History Lessons',
    content: 'Learn about a new historical event every day.',
    startDate: [2023, 10, 1],
    endDate: [2023, 10, 31],
    currentParticipants: 7,
    maxParticipants: 7
  },
  {
    planetId: 30,
    planetImg: 'https://example.com/image30.jpg',
    category: 'ETC',
    name: 'Gardening',
    content: 'Tend to your garden every day and watch it flourish.',
    startDate: [2023, 11, 1],
    endDate: [2023, 11, 30],
    currentParticipants: 7,
    maxParticipants: 10
  }
];

export default challenges;
