server:
  port: 8002

spring:
  data:
   redis:
     host: localhost
     port: 6380
   mongodb:
     uri: mongodb://localhost:27017/testdb
     host: localhost
     port: 27017
  jackson:
   serialization:
     WRITE_DATES_AS_TIMESTAMPS: false
   date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX