server:
  port: 8002

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${MYSQL_MASTER_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      uri: ${MONGODB_URI}

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: Asia/Seoul