server:
  port: 8002

spring:
  datasource:
    url: ${MYSQL_SLAVE_URL}
    driver-class-name: org.h2.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      uri: ${MONGODB_URI}
      host: mongo
      port: 27017
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: Asia/Seoul