spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:file:~/testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      example: DEBUG

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  salt: ${JWT_SALT}
  access-token:
    expiretime: ${JWT_ACCESS_TOKEN_EXPIRETIME}
  refresh-token:
    expiretime: ${JWT_REFRESH_TOKEN_EXPIRETIME}

kakao:
  secret:
    key: ${KAKAO_SECRET_KEY}
  loginurl: ${KAKAO_LOGIN_URL}
  logouturl: ${KAKAO_LOGOUT_URL}

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ${AWS_S3_BUCKET_REGION}
    stack:
      auto: false
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}

